### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by ljp1997** [NavyZeng/Diff-Unmix#3]
Dear Author,
I am very interested in your work on Diff-Unmix . Could you please provide some details on the GPU requirements for training? Specifically:

How many GPUs are needed to train Diff-Unmix effectively?
What GPU  did you use to train this model?
Thank you very much for your assistance.

Best regards,
Li

**Comment by NavyZeng** [comment]
Dear Li, 

Thank you for your patience. 

2xRTX4060ti-16GB were used.

Kind regards
