### ISSUE TITLE
Request for Access to Pre-Trained Models

### ISSUE THREAD

**Issue by Changyuan0825** [NavyZeng/Diff-Unmix#4]
Dear Haijin Zeng,

I am thoroughly impressed by your work and the pre-trained models you have shared. However, I currently do not have permission to access the pre-trained condition function and spectral unmixing network on Google Drive. Could you kindly grant me access (My Google email address is wangchangyuan0825@gmail.com). I would greatly appreciate it if you could provide me with the necessary permissions.

Looking forward to your kind assistance.

Sincerely,
Changyuan

**Comment by NavyZeng** [comment]
Dear Changyuan,

Thank you for your patience, I have just shared the permission.

Kind regards,
Haijin

**Comment by Changyuan0825** [comment]
Dear Haijin,

Thanks for your help.

Yours Sincerely,
Changyuan
